pipeline {
  agent any
  environment {
    SONAR_TOKEN = credentials('SONAR_TOKEN')
  }
  stages {
      stage('CodeInspection') {
        steps {
          sh 'chmod +x gradlew'
          sh './gradlew sonarqube'
        }

      }
      stage('AcceptanceTest') {
        steps {
          sh './gradlew test'
        }
        post {
          always {
            junit 'build/test-results/test/*.xml'
            archiveArtifacts 'build/reports/tests/test/index.html'
            archiveArtifacts artifacts: 'logs/todoly.log', fingerprint: true
          }
        }
      }
  }
  post {
      always {
        emailext body: 'Hi Tojoris!, this is the link!\nClick here: $BUILD_URL\nHave a nice day!!!',
        subject: '$BUILD_STATUS! - Pipeline status and link of the pipeline log',
        to: 'todolytojoris@gmail.com'
      }
    }
}
